-- Pilot on ONE cashier database. Run with a verified SELECT-only Firebird user.
-- These statements inspect system metadata only; they do not read warehouse rows.
SET LIST ON;
SET TRANSACTION READ ONLY READ COMMITTED RECORD_VERSION NO WAIT;

SELECT FIRST 100 TRIM(r.RDB$RELATION_NAME) AS RELATION_NAME,
       CASE WHEN r.RDB$VIEW_BLR IS NOT NULL THEN 1 ELSE 0 END AS IS_VIEW
FROM RDB$RELATIONS r
WHERE COALESCE(r.RDB$SYSTEM_FLAG, 0) = 0
  AND (r.RDB$RELATION_NAME CONTAINING 'WAREBASE'
       OR r.RDB$RELATION_NAME CONTAINING 'STOCK'
       OR r.RDB$RELATION_NAME CONTAINING 'RESERV')
ORDER BY r.RDB$RELATION_NAME;

SELECT FIRST 300 TRIM(rf.RDB$RELATION_NAME) AS RELATION_NAME,
       rf.RDB$FIELD_POSITION AS POSITION,
       TRIM(rf.RDB$FIELD_NAME) AS FIELD_NAME,
       f.RDB$FIELD_TYPE AS FIELD_TYPE,
       f.RDB$FIELD_SUB_TYPE AS FIELD_SUB_TYPE,
       f.RDB$FIELD_SCALE AS FIELD_SCALE,
       f.RDB$FIELD_LENGTH AS FIELD_LENGTH
FROM RDB$RELATION_FIELDS rf
JOIN RDB$FIELDS f ON f.RDB$FIELD_NAME = rf.RDB$FIELD_SOURCE
WHERE rf.RDB$RELATION_NAME CONTAINING 'WAREBASE'
   OR rf.RDB$RELATION_NAME CONTAINING 'STOCK'
   OR rf.RDB$RELATION_NAME CONTAINING 'RESERV'
ORDER BY rf.RDB$RELATION_NAME, rf.RDB$FIELD_POSITION;

SELECT FIRST 200 TRIM(i.RDB$RELATION_NAME) AS RELATION_NAME,
       TRIM(i.RDB$INDEX_NAME) AS INDEX_NAME,
       i.RDB$INDEX_INACTIVE AS INACTIVE,
       s.RDB$FIELD_POSITION AS POSITION,
       TRIM(s.RDB$FIELD_NAME) AS FIELD_NAME
FROM RDB$INDICES i
JOIN RDB$INDEX_SEGMENTS s ON s.RDB$INDEX_NAME = i.RDB$INDEX_NAME
WHERE i.RDB$RELATION_NAME CONTAINING 'WAREBASE'
   OR i.RDB$RELATION_NAME CONTAINING 'STOCK'
   OR i.RDB$RELATION_NAME CONTAINING 'RESERV'
ORDER BY i.RDB$RELATION_NAME, i.RDB$INDEX_NAME, s.RDB$FIELD_POSITION;

ROLLBACK;
