#!/bin/sh
set -eu
: "${STOCK_PG_APP_PASSWORD:?STOCK_PG_APP_PASSWORD is required}"
: "${STOCK_PG_OWNER_PASSWORD:?STOCK_PG_OWNER_PASSWORD is required}"
psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
  -v ON_ERROR_STOP=1 -v app_password="$STOCK_PG_APP_PASSWORD" \
  -v owner_password="$STOCK_PG_OWNER_PASSWORD" <<'SQL'
CREATE ROLE stock_schema_owner LOGIN PASSWORD :'owner_password'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE stock_app LOGIN PASSWORD :'app_password'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
ALTER DATABASE stocks OWNER TO stock_schema_owner;
REVOKE CONNECT ON DATABASE stocks FROM PUBLIC;
GRANT CONNECT ON DATABASE stocks TO stock_schema_owner;
GRANT CONNECT ON DATABASE stocks TO stock_app;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
SQL
