[Service]
CacheDirectory=inkar-shop
Environment=MEDUSA_CACHE_DIR=/var/cache/inkar-shop/medusa
SuccessExitStatus=143
ExecStartPre=/usr/bin/mkdir -p /var/www/inkar-shop/.next/standalone/public
ExecStartPre=/usr/bin/cp -a /var/www/inkar-shop/public/. /var/www/inkar-shop/.next/standalone/public/
ExecStartPre=/usr/bin/mkdir -p /var/www/inkar-shop/.next/standalone/.next/static
ExecStartPre=/usr/bin/cp -a /var/www/inkar-shop/.next/static/. /var/www/inkar-shop/.next/standalone/.next/static/
