package kz.epharm.catalog.service

import kz.epharm.shared.error.AppException
import kz.epharm.shared.error.ErrorCode
import org.springframework.http.HttpStatus
import org.springframework.jdbc.core.JdbcTemplate
import org.springframework.stereotype.Repository
import java.time.Instant
import java.util.UUID

/** Stable ACC scope keys are generated by the offline, reviewed catalogue import. */
enum class AccScopeKind(val wire: String, val keyColumn: String, val labelColumn: String, val parentColumn: String?) {
    GROUP("acc_group", "group_key", "group_label", null),
    SUBGROUP("acc_subgroup", "subgroup_key", "subgroup_label", "group_label"),
    MNN("acc_mnn", "mnn_key", "mnn_label", null);

    companion object {
        fun parse(raw: String): AccScopeKind = entries.firstOrNull { it.wire == raw }
            ?: throw AppException(
                ErrorCode.VALIDATION_FAILED,
                "Unsupported ACC trigger kind: $raw",
                HttpStatus.BAD_REQUEST,
            )
    }
}

data class AccCatalogSnapshotDto(
    val sha256: String,
    val sourceName: String,
    val itemCount: Int,
    val barcodeCount: Int,
    val importedAt: Instant,
)

data class AccScopeOptionDto(
    val key: String,
    val label: String,
    val parentLabel: String?,
    /** Number of distinct WARE_ID values with at least one unambiguous barcode. */
    val count: Int,
)

data class AccScopeOptionsDto(
    val snapshot: AccCatalogSnapshotDto?,
    val options: List<AccScopeOptionDto>,
)

data class AccCatalogClassification(
    val wareId: String,
    val barcode: String,
    val groupKey: String?,
    val subgroupKey: String?,
    val mnnKey: String?,
) {
    fun matches(kind: AccScopeKind, key: String): Boolean = when (kind) {
        AccScopeKind.GROUP -> groupKey == key
        AccScopeKind.SUBGROUP -> subgroupKey == key
        AccScopeKind.MNN -> mnnKey == key
    }
}

/**
 * Read-only access to the active, immutable ACC snapshot. A barcode linked to two source WARE_IDs
 * is deliberately omitted from POSM matching, even when both rows happen to share a category.
 */
@Repository
class AccCatalogTaxonomy(private val jdbc: JdbcTemplate) {
    private data class ActiveSnapshot(val id: UUID, val dto: AccCatalogSnapshotDto)

    fun activeSnapshot(): AccCatalogSnapshotDto? = loadActiveSnapshot()?.dto

    private fun loadActiveSnapshot(): ActiveSnapshot? = jdbc.query(
        """
        SELECT s.id, s.sha256, s.source_name, s.item_count, s.barcode_count, s.imported_at
          FROM acc_catalog_snapshots s
          JOIN acc_catalog_state state ON state.active_snapshot_id = s.id
         WHERE state.singleton = 1
        """.trimIndent(),
        { rs, _ ->
            ActiveSnapshot(
                id = rs.getObject("id", UUID::class.java),
                dto = AccCatalogSnapshotDto(
                    sha256 = rs.getString("sha256"),
                    sourceName = rs.getString("source_name"),
                    itemCount = rs.getInt("item_count"),
                    barcodeCount = rs.getInt("barcode_count"),
                    importedAt = rs.getTimestamp("imported_at").toInstant(),
                ),
            )
        },
    ).firstOrNull()

    fun options(kind: AccScopeKind, q: String? = null): AccScopeOptionsDto {
        val snapshot = loadActiveSnapshot() ?: return AccScopeOptionsDto(null, emptyList())
        val key = kind.keyColumn
        val label = kind.labelColumn
        val parent = kind.parentColumn?.let { "MIN(b.$it)" } ?: "NULL::varchar"
        val search = q?.trim().orEmpty().take(120)
        val havingSearch = when {
            search.isEmpty() -> ""
            kind.parentColumn != null ->
                "HAVING bool_or(b.$label ILIKE ? ESCAPE '!' OR b.${kind.parentColumn} ILIKE ? ESCAPE '!')"
            else -> "HAVING bool_or(b.$label ILIKE ? ESCAPE '!')"
        }
        val pattern = "%${escapeLike(search)}%"
        val args: Array<Any> = when {
            search.isEmpty() -> arrayOf(snapshot.id, snapshot.id)
            kind.parentColumn != null -> arrayOf(snapshot.id, snapshot.id, pattern, pattern)
            else -> arrayOf(snapshot.id, snapshot.id, pattern)
        }
        val rows = jdbc.query(
            """
            WITH unique_barcodes AS (
                SELECT b.barcode
                  FROM acc_catalog_barcodes b WHERE b.snapshot_id = ?
                 GROUP BY b.barcode HAVING count(*) = 1
            )
            SELECT b.$key AS key, MIN(b.$label) AS label, $parent AS parent_label,
                   count(DISTINCT b.ware_id) AS member_count
              FROM acc_catalog_barcodes b
              JOIN unique_barcodes u ON u.barcode = b.barcode
             WHERE b.snapshot_id = ? AND b.$key IS NOT NULL
             GROUP BY b.$key
             $havingSearch
             ORDER BY label, key
             LIMIT 100
            """.trimIndent(),
            { rs, _ ->
                AccScopeOptionDto(
                    key = rs.getString("key"),
                    label = rs.getString("label"),
                    parentLabel = rs.getString("parent_label"),
                    count = rs.getInt("member_count"),
                )
            },
            *args,
        )
        return AccScopeOptionsDto(snapshot.dto, rows)
    }

    fun requireActiveOption(kind: AccScopeKind, key: String): AccScopeOptionDto {
        val clean = key.trim()
        if (clean.isEmpty() || clean.length > 40) invalidScope(kind, clean)
        val keyColumn = kind.keyColumn
        val labelColumn = kind.labelColumn
        val parent = kind.parentColumn?.let { "MIN(b.$it)" } ?: "NULL::varchar"
        return jdbc.query(
            """
            WITH active AS (
                SELECT active_snapshot_id AS id FROM acc_catalog_state WHERE singleton = 1
            ), unique_barcodes AS (
                SELECT b.barcode
                  FROM acc_catalog_barcodes b JOIN active a ON a.id = b.snapshot_id
                 GROUP BY b.barcode HAVING count(*) = 1
            )
            SELECT b.$keyColumn AS key, MIN(b.$labelColumn) AS label,
                   $parent AS parent_label, count(DISTINCT b.ware_id) AS member_count
              FROM acc_catalog_barcodes b
              JOIN active a ON a.id = b.snapshot_id
              JOIN unique_barcodes u ON u.barcode = b.barcode
             WHERE b.$keyColumn = ?
             GROUP BY b.$keyColumn
            """.trimIndent(),
            { rs, _ ->
                AccScopeOptionDto(
                    key = rs.getString("key"),
                    label = rs.getString("label"),
                    parentLabel = rs.getString("parent_label"),
                    count = rs.getInt("member_count"),
                )
            },
            clean,
        ).firstOrNull() ?: invalidScope(kind, clean)
    }

    /** Exact EAN lookup only. Missing and duplicate source barcodes are absent from the result. */
    fun unambiguousBarcodes(barcodes: Collection<String>): Map<String, AccCatalogClassification> {
        val clean = barcodes.map(String::trim).filter(String::isNotEmpty).distinct()
        if (clean.isEmpty()) return emptyMap()
        val snapshotId = loadActiveSnapshot()?.id ?: return emptyMap()
        val rows = clean.chunked(200).flatMap { chunk ->
            val placeholders = chunk.joinToString(",") { "?" }
            jdbc.query(
                """
            SELECT b.ware_id, b.barcode, b.group_key, b.subgroup_key, b.mnn_key
              FROM acc_catalog_barcodes b
             WHERE b.snapshot_id = ? AND b.barcode IN ($placeholders)
            """.trimIndent(),
                { rs, _ ->
                    AccCatalogClassification(
                        wareId = rs.getString("ware_id"),
                        barcode = rs.getString("barcode"),
                        groupKey = rs.getString("group_key"),
                        subgroupKey = rs.getString("subgroup_key"),
                        mnnKey = rs.getString("mnn_key"),
                    )
                },
                snapshotId,
                *chunk.toTypedArray(),
            )
        }
        return rows.groupBy(AccCatalogClassification::barcode)
            .mapNotNull { (barcode, candidates) ->
                candidates.singleOrNull()?.let { barcode to it }
            }.toMap()
    }

    private fun escapeLike(value: String) = value.replace("!", "!!").replace("%", "!%").replace("_", "!_")

    private fun invalidScope(kind: AccScopeKind, key: String): Nothing = throw AppException(
        ErrorCode.VALIDATION_FAILED,
        "ACC scope ${kind.wire}/$key is not present in the active catalogue or has no unambiguous barcode",
        HttpStatus.BAD_REQUEST,
    )
}
